---
dw_packages:
  - git-core
  - apache2-mpm-prefork
  - libapache2-mod-perl2
  - libapache2-mod-apreq2
  - libapache2-request-perl
  - mysql-server
  - wget
  - unzip
  - links
  - vim
  - libclass-autouse-perl
  - libdatetime-perl
  - libcache-memcached-perl
  - libhash-multivalue-perl
  - libgd-gd2-perl
  - libhtml-template-perl
  - libwww-perl
  - libmime-lite-perl
  - libnet-dns-perl
  - liburi-perl
  - libxml-simple-perl
  - libclass-accessor-perl
  - libclass-data-inheritable-perl
  - libclass-trigger-perl
  - libcrypt-dh-perl
  - libmath-bigint-gmp-perl
  - liburi-fetch-perl
  - libgd-graph-perl
  - libgnupg-interface-perl
  - libmail-gnupg-perl
  - perlmagick
  - libproc-processtable-perl
  - libsoap-lite-perl
  - librpc-xml-perl
  - libstring-crc32-perl
  - libtext-vcard-perl
  - libxml-atom-perl
  - libxml-rss-perl
  - libimage-size-perl
  - libunicode-maputf8-perl
  - libgtop2-dev
  - build-essential
  - libnet-openid-consumer-perl
  - libnet-openid-server-perl
  - libyaml-perl
  - libcaptcha-recaptcha-perl
  - libdbd-sqlite3-perl
  - libtest-simple-perl
  - libtemplate-perl
  - libterm-readkey-perl
  - libmime-base64-urlsafe-perl
  - gcc
  - libtest-most-perl
  - libgearman-client-perl
  - libfile-find-rule-perl
  - libbusiness-creditcard-perl
  - liblwpx-paranoidagent-perl
  - libtheschwartz-perl
  - libfile-type-perl
  - libjson-perl
  - libdanga-socket-perl
  - libio-aio-perl
  - libsys-syscall-perl
  - ruby
  - postfix
  - cpanminus
  - python-pip
  - python-mysqldb

dw_cpan:
  - GTop
  - Digest::SHA1
  - Unicode::CheckUTF8
  - MogileFS::Client
  - TheSchwartz::Worker::SendEmail
  - Digest::SHA256
  - Text::Markdown
  - Image::ExifTool
  - Net::OAuth
  - LWP::UserAgent::Paranoid
  - Mozilla::CA
  - Net::SMTPS
  - XMLRPC::Lite
  - Locale::Country
  - IP::Country::Fast

dw_pip:
  - pexpect

dw_gem:
  - { name: 'sass', version: '3.2.19' }
  - { name: 'compass', version: '0.12.2' }
